parameters:
#    flighthub_test_legacy.example.class: Flighthub\TestLegacyBundle\Example

services:
#    flighthub_test_legacy.example:
#        class: %flighthub_test_legacy.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
